[Paths]
backgroundPaths = [ "Assets/Backgrounds",]
musicPaths = [ "Assets/Music",]
outputPath = "Output"
memesPath = "Assets/Memes"
imgurPath = "Assets/Memes"
redditPath = "Assets/Memes"

[Settings]
clipFps = 60
clipDuration = 4

[Display]
paddingTop = 100
paddingBottom = 100
paddingSide = 50

[AutoPosting]
Credentials = "path-here"
YouTube-Api-Version = "v3"
YouTube-Api-Service-Name = "youtube"
subReddits = [ "memes", "dankmemes",]
shortsAmount = 5

[Scraping.Imgur]
Authorization = "key-here"

[Scraping.Reddit]
Id = "id-here"
Secret = "secret-here"
userAgent = "Serialized's Cloud Tool"
TimeSpan = "Day"
